### ISSUE TITLE
node error when running `npm run dev`

### ISSUE THREAD

**Issue by sonofmun** [deep-reader/DeepReader#84]
It throws this error:

```
> vue-me@1.0.0 dev /home/matt/DeepReader
> node build/dev-server.js


/home/matt/DeepReader/build/dev-server.js:32
  log: () => {}
        ^
SyntaxError: Unexpected token )
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
npm ERR! weird error 8
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! not ok code 0
```

I solved this by upgrading to the newest version of nodejs using the instructions here: https://www.digitalocean.com/community/tutorials/how-to-install-node-js-on-ubuntu-16-04
Perhaps adding this fix to the documentation could be useful?

**Comment by brosner** [comment]
Agreed. The `package.json` metadata is incorrect and should also reflect the correct information. Thanks for letting us know!

**Comment by jtauber** [comment]
As well as `package.json` is it a case of better documentation of the node version requirement in the README?
